### ISSUE TITLE
USER STORY: Analize Poll

### ISSUE THREAD

**Issue by fabi8bit** [fabi8bit/love-running#2]
As a **admin** I can **go through the data selected by users** so that **I can create charts**

## Acceptance Criteria:
- Acceptance Criteria 1: Dashboard showing the percentage for every option
- Acceptance Criteria 2: Possibility to display different type of charts (pye charts, bar chart)
- Acceptance Criteria 3:

## Tasks:
- [ ] Evaluate data collected
- [ ] Design the interface for dashboard
- [ ] Export data as csv
